### ISSUE TITLE
The Domain Adaptation Layer (partial) and Lossless Size Adaptation methodologies were avoided in this implementation.

### ISSUE THREAD

**Issue by mayilin0714** [Muntasir13/Face-Spoofing-Detection-using-Depth-Wise-Convolution#2]
if you have the code of The Domain Adaptation Layer (partial) and Lossless Size Adaptation methodologies ?

**Comment by Muntasir13** [comment]
You can find the Domain Adaptation Layer code in the model_arch.py file. This is only partially implemented. The Lossless Size Adaptation from the paper was not implemented here, as I did not understand how it was originally implemented
